{% set name = "vollseg-napari-mtrack" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vollseg-napari-mtrack-{{ version }}.tar.gz
  sha256: 650351988bb22e05e6b46b5e4e8a32e182e271979dc7228947c3868f54292873

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }},<3.11
    - qtpy
    - tifffile

test:
  imports:
    - vollseg_napari_mtrack
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kapoorlabs-CAPED/vollseg-napari-mtrack
  summary: |
    Segment kymographs of microtubules, actin filaments and perform Ransac
    based fits to compute dynamic instability parameters for individual
    kymographs and also in batch
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kapoorlab
