{% set name = "vollseg-napari-mtrack" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-napari-mtrack-{{ version }}.tar.gz
  sha256: 23161fd38ab3bb820dbecfbbde8a98e0b693f63646398bd73194370e50a50449

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8,<3.11
    - qtpy
    - tifffile

test:
  imports:
    - vollseg_napari_mtrack
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/vollseg-napari-mtrack
  summary: |
    Segment kymographs of microtubules, actin filaments and perform Ransac
    based fits to compute dynamic instability parameters for individual
    kymographs and also in batch
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kapoorlab
